version: "3.3"

services:
  # The name of the service to run
  server:
    build:
      # The path to the service's repository
      context: .
      dockerfile: ./Dockerfile
      target: test
    # bind the service's exposed port 80 to the host's 8222
    restart: unless-stopped
    depends_on:
      - server-db
    # export useful environment variables to the service
    environment:
      - SERVER_DB_HOST=server-db
      - SERVER_DB_PORT=27017
      - SERVER_DB_NAME=server-db
      - ROOT_PATH=

  server-db:
    # use existing mongo image from dockerhub
    image: mongo
    container_name: server-db
    restart: unless-stopped
    # export useful environment variables to the service's container
    environment:
      - PUID=1000
      - PGID=1000
