name: Server Stage

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

  push:
    branches: [ development ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Check current user
        run: whoami

      - name: Check out code
        uses: actions/checkout@v2

      - name: Where/When am I in context of the GIT?
        run: git status

      - name: List
        run: ls -lah

      - name: Docker-Compose
        run: docker-compose -f docker-compose-stage.yml -p server-deployment up -d --build
